### ISSUE TITLE
Documentação das sprints

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2018.1-IncluCare_API#29]
Planning:
- [ ] papeis

- [ ] pareamento

- [ ] planejamento

- [ ] pontuação

Resultados

- [ ] Review (o que foi entregue do planejado)

- [ ] Velocity

- [ ] Retrospectiva

- [ ] burndown - commits por dia

- [ ] Metricas (cobertura/qualidade de codigo)

- [ ] Análise do Scrum Master sobre a sprint orientada aos indicadores

**Comment by byronkamal** [comment]
Documentação já está sendo feita.
