### ISSUE TITLE
Atualizar nome e email - devise

### ISSUE THREAD

**Issue by byronkamal** [fga-gpp-mds/2018.1-IncluCare_API#99]
Estou tentando alterar o email e o nome no back-end, pela rota: localhost:3000/auth com PUT, e não achei quais informações parâmetros mandar para realizar a troca. No angular2-token (front-end) não existe a opção update user.

**Comment by byronkamal** [comment]
Obs: passei ontem o dia pesquisando como resolver esse problema e não achei solução.

**Comment by roginaldosemog** [comment]
A função mais parecida com "updateTeamMember" seria a updatePassword, que atualiza a senha do usuário, para criar um novo método, não podemos editar diretamente nos node-modules, então precisaríamos seguir alguns passos:
1) Criar um novo serviço que estende as funcionalidades do angular2-token;
2) Substituir todas as imports diretas ao Angular2TokenService para esse novo serviço;
3) Criar um método novo dentro desse serviço, baseado nessa função https://github.com/neroniaky/angular2-token#updatepassword;
4) Fazer alterações necessárias no backend durante o processo, caso seja necessário permitir a passagem de novos parâmetros (Assim como tive de fazer pra adicionar o nome de usuário).

**Comment by byronkamal** [comment]
Tentei essa solução, mas não resolveu o problema. Dentro do angular2-token  os parametros são enviados automaticamente para o back. Existe um padrão do que é enviado para o back e para alterar esse padrão seria necessário alterar muita coisa dentro deste module.

**Comment by byronkamal** [comment]
**Solução encontrada:**
O angular2-token tem uma opção de criar uma função personalizada de requisição, como é possível ver em [https://github.com/neroniaky/angular2-token#http-service-wrapper](url). Apliquei está solução ao projeto e consegui fazer a troca do nome e email do usuário.
